""""""""""""""""""""""""""""""""""""
set nocompatible              " required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
" Vundle Plugins Start
" --------------------
Plugin 'vim-airline/vim-airline'
let g:airline#extensions#branch#enabled=1
Plugin 'scrooloose/syntastic'
Plugin 'nvie/vim-flake8'
Plugin 'scrooloose/nerdcommenter'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

call vundle#end()
filetype plugin on
" Vundle Plugins End
" ------------------

""""""""""""""""""""""""""""""""""""
" commen
set encoding=utf-8
set fileformats=unix,dos,mac
set backspace=2
set shell=/usr/local/bin/zsh
set updatetime=250
"set foldmethod=indent

" highlight
syntax on
colorscheme luna
set hlsearch
set ruler
set nu

" split window
set splitbelow
set splitright
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" nmap
nnoremap ]h <Plug>GitGutterDisable
nnoremap [h <Plug>GitGutterEnable

" command line
set cmdheight=2
set laststatus=2
set showcmd

" tab
set autoindent
set smartindent
set cindent
set shiftwidth=4
set tabstop=4
set expandtab
set softtabstop=4

" autocmd
au FileType python nnoremap <buffer> <F5> :exec '!python' shellescape(@%, 1)<cr>
au FileType lua nnoremap <buffer> <F5> :exec '!lua' shellescape(@%, 1)<cr>
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

